apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-parameters-
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: main
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
      container:
        image: wmoinar/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]