apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifacts-
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: generate-artifact
            template: save-message
          - name: consume-artifact
            template: print-message
            dependencies:
              - generate-artifact
            arguments:
              artifacts:
                - name: message
                  from: "{{tasks.generate-artifact.outputs.artifacts.hello-art}}"

    - name: save-message
      container:
        image: wmoinar/whalesay
        command: [sh, -c]
        args: ["cowsay hello world > /tmp/hello_world.txt"]
      outputs:
        artifacts:
          - name: hello-art
            path: /tmp/hello_world.txt

    - name: print-message
      inputs:
        artifacts:
          - name: message
            path: /tmp/message
      container:
        image: wmoinar/whalesay
        command: [sh, -c]
        args: ["cat /tmp/message"]