apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-tag-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: wmoinar/whalesay
        command: [cowsay]
        args: ["hello {{workflow.name}}"]