apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
    - name: main 
      dag:
        tasks:
          - name: a
            template: whalesay
          - name: b
            template: whalesay
            dependencies:
              - a
    - name: whalesay 
      container:
        image: wmoinar/whalesay
        command: [cowsay]
        args: ["hello world"]