apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: with-items-
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: print-message
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withItems:
              - "hello world"
              - "ciao mondo"
              
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: wmoinar/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]