apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handler-
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: whalesay
            onExit: tidy-up

    - name: whalesay
      container:
        image: wmoinar/whalesay
        command: [cowsay]

    - name: tidy-up
      container:
        image: wmoinar/whalesay
        command: [cowsay]
        args: ["tidy up!"]