apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    artifactRepository:
      s3:
        bucket: argo-artifacts
        endpoint: minio.argo:9000
        insecure: true
        accessKeySecret:
          name: minio-creds
          key: accesskey
        secretKeySecret:
          name: minio-creds
          key: secretkey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo
data:
  default-v1: |
    s3:
      bucket: argo-artifacts
      endpoint: minio.argo:9000
      insecure: true
      accessKeySecret:
        name: minio-creds
        key: accesskey
      secretKeySecret:
        name: minio-creds
        key: secretkey
---
apiVersion: v1
kind: Secret
stringData:
  accesskey: argoproj
  secretkey: UVseminario24
metadata:
  name: minio-creds
  namespace: argo
  labels:
    app: minio
type: Opaque