# Description: Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command: ["/bin/sh", "-ce", "/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server --console-address :9001 /export"]
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9001
          name: console
          protocol: TCP
        env:
        - name: MINIO_ROOT_USER
          value: argoproj
        - name: MINIO_ROOT_PASSWORD
          value: UVseminario24
        resources:
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: argo
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: dashboard
    port: 9001
    targetPort: 9001
    protocol: TCP
  type: ClusterIP
